<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="AutoMapper" Version="13.0.1" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Hotels\" />
      <Folder Include="HotelRooms\" />
      <Folder Include="Permissions\" />
      <Folder Include="RoomTypes\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\HotelChain.DataAccess\HotelChain.DataAccess.csproj" />
      <ProjectReference Include="..\HotelChain.Repository\HotelChain.Repository.csproj" />
    </ItemGroup>

</Project>
